// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/grigory/url-shortener/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// FindByOriginalURL provides a mock function with given fields: ctx, originalURL
func (_m *MockRepository) FindByOriginalURL(ctx context.Context, originalURL string) (domain.URL, error) {
	ret := _m.Called(ctx, originalURL)

	if len(ret) == 0 {
		panic("no return value specified for FindByOriginalURL")
	}

	var r0 domain.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.URL, error)); ok {
		return rf(ctx, originalURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.URL); ok {
		r0 = rf(ctx, originalURL)
	} else {
		r0 = ret.Get(0).(domain.URL)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, originalURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FindByOriginalURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByOriginalURL'
type MockRepository_FindByOriginalURL_Call struct {
	*mock.Call
}

// FindByOriginalURL is a helper method to define mock.On call
//   - ctx context.Context
//   - originalURL string
func (_e *MockRepository_Expecter) FindByOriginalURL(ctx interface{}, originalURL interface{}) *MockRepository_FindByOriginalURL_Call {
	return &MockRepository_FindByOriginalURL_Call{Call: _e.mock.On("FindByOriginalURL", ctx, originalURL)}
}

func (_c *MockRepository_FindByOriginalURL_Call) Run(run func(ctx context.Context, originalURL string)) *MockRepository_FindByOriginalURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_FindByOriginalURL_Call) Return(_a0 domain.URL, _a1 error) *MockRepository_FindByOriginalURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FindByOriginalURL_Call) RunAndReturn(run func(context.Context, string) (domain.URL, error)) *MockRepository_FindByOriginalURL_Call {
	_c.Call.Return(run)
	return _c
}

// FindByShortCode provides a mock function with given fields: ctx, shortCode
func (_m *MockRepository) FindByShortCode(ctx context.Context, shortCode string) (domain.URL, error) {
	ret := _m.Called(ctx, shortCode)

	if len(ret) == 0 {
		panic("no return value specified for FindByShortCode")
	}

	var r0 domain.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.URL, error)); ok {
		return rf(ctx, shortCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.URL); ok {
		r0 = rf(ctx, shortCode)
	} else {
		r0 = ret.Get(0).(domain.URL)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FindByShortCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByShortCode'
type MockRepository_FindByShortCode_Call struct {
	*mock.Call
}

// FindByShortCode is a helper method to define mock.On call
//   - ctx context.Context
//   - shortCode string
func (_e *MockRepository_Expecter) FindByShortCode(ctx interface{}, shortCode interface{}) *MockRepository_FindByShortCode_Call {
	return &MockRepository_FindByShortCode_Call{Call: _e.mock.On("FindByShortCode", ctx, shortCode)}
}

func (_c *MockRepository_FindByShortCode_Call) Run(run func(ctx context.Context, shortCode string)) *MockRepository_FindByShortCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_FindByShortCode_Call) Return(_a0 domain.URL, _a1 error) *MockRepository_FindByShortCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FindByShortCode_Call) RunAndReturn(run func(context.Context, string) (domain.URL, error)) *MockRepository_FindByShortCode_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, u
func (_m *MockRepository) Save(ctx context.Context, u domain.URL) error {
	ret := _m.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.URL) error); ok {
		r0 = rf(ctx, u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - u domain.URL
func (_e *MockRepository_Expecter) Save(ctx interface{}, u interface{}) *MockRepository_Save_Call {
	return &MockRepository_Save_Call{Call: _e.mock.On("Save", ctx, u)}
}

func (_c *MockRepository_Save_Call) Run(run func(ctx context.Context, u domain.URL)) *MockRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.URL))
	})
	return _c
}

func (_c *MockRepository_Save_Call) Return(_a0 error) *MockRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Save_Call) RunAndReturn(run func(context.Context, domain.URL) error) *MockRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
