// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/grigory/url-shortener/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockURLShortener is an autogenerated mock type for the URLShortener type
type MockURLShortener struct {
	mock.Mock
}

type MockURLShortener_Expecter struct {
	mock *mock.Mock
}

func (_m *MockURLShortener) EXPECT() *MockURLShortener_Expecter {
	return &MockURLShortener_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function with given fields: ctx, shortCode
func (_m *MockURLShortener) Resolve(ctx context.Context, shortCode string) (domain.URL, error) {
	ret := _m.Called(ctx, shortCode)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 domain.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.URL, error)); ok {
		return rf(ctx, shortCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.URL); ok {
		r0 = rf(ctx, shortCode)
	} else {
		r0 = ret.Get(0).(domain.URL)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLShortener_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockURLShortener_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
//   - shortCode string
func (_e *MockURLShortener_Expecter) Resolve(ctx interface{}, shortCode interface{}) *MockURLShortener_Resolve_Call {
	return &MockURLShortener_Resolve_Call{Call: _e.mock.On("Resolve", ctx, shortCode)}
}

func (_c *MockURLShortener_Resolve_Call) Run(run func(ctx context.Context, shortCode string)) *MockURLShortener_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockURLShortener_Resolve_Call) Return(_a0 domain.URL, _a1 error) *MockURLShortener_Resolve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLShortener_Resolve_Call) RunAndReturn(run func(context.Context, string) (domain.URL, error)) *MockURLShortener_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// Shorten provides a mock function with given fields: ctx, originalURL
func (_m *MockURLShortener) Shorten(ctx context.Context, originalURL string) (domain.URL, error) {
	ret := _m.Called(ctx, originalURL)

	if len(ret) == 0 {
		panic("no return value specified for Shorten")
	}

	var r0 domain.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.URL, error)); ok {
		return rf(ctx, originalURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.URL); ok {
		r0 = rf(ctx, originalURL)
	} else {
		r0 = ret.Get(0).(domain.URL)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, originalURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLShortener_Shorten_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shorten'
type MockURLShortener_Shorten_Call struct {
	*mock.Call
}

// Shorten is a helper method to define mock.On call
//   - ctx context.Context
//   - originalURL string
func (_e *MockURLShortener_Expecter) Shorten(ctx interface{}, originalURL interface{}) *MockURLShortener_Shorten_Call {
	return &MockURLShortener_Shorten_Call{Call: _e.mock.On("Shorten", ctx, originalURL)}
}

func (_c *MockURLShortener_Shorten_Call) Run(run func(ctx context.Context, originalURL string)) *MockURLShortener_Shorten_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockURLShortener_Shorten_Call) Return(_a0 domain.URL, _a1 error) *MockURLShortener_Shorten_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLShortener_Shorten_Call) RunAndReturn(run func(context.Context, string) (domain.URL, error)) *MockURLShortener_Shorten_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockURLShortener creates a new instance of MockURLShortener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockURLShortener(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockURLShortener {
	mock := &MockURLShortener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
