// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	GetURLByOriginalURL(ctx context.Context, originalUrl string) (Url, error)
	GetURLByShortCode(ctx context.Context, shortCode string) (Url, error)
	InsertURL(ctx context.Context, arg InsertURLParams) (Url, error)
}

var _ Querier = (*Queries)(nil)
