// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package postgres

import (
	"context"
)

const getURLByOriginalURL = `-- name: GetURLByOriginalURL :one
SELECT id, short_code, original_url, created_at
FROM urls
WHERE original_url = $1
LIMIT 1
`

func (q *Queries) GetURLByOriginalURL(ctx context.Context, originalUrl string) (Url, error) {
	row := q.db.QueryRow(ctx, getURLByOriginalURL, originalUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getURLByShortCode = `-- name: GetURLByShortCode :one
SELECT id, short_code, original_url, created_at
FROM urls
WHERE short_code = $1
LIMIT 1
`

func (q *Queries) GetURLByShortCode(ctx context.Context, shortCode string) (Url, error) {
	row := q.db.QueryRow(ctx, getURLByShortCode, shortCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.CreatedAt,
	)
	return i, err
}

const insertURL = `-- name: InsertURL :one
INSERT INTO urls (short_code, original_url)
VALUES ($1, $2)
RETURNING id, short_code, original_url, created_at
`

type InsertURLParams struct {
	ShortCode   string `json:"short_code"`
	OriginalUrl string `json:"original_url"`
}

func (q *Queries) InsertURL(ctx context.Context, arg InsertURLParams) (Url, error) {
	row := q.db.QueryRow(ctx, insertURL, arg.ShortCode, arg.OriginalUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.CreatedAt,
	)
	return i, err
}
